### ISSUE TITLE
new PCB version MX-USBISP-V5.00

### ISSUE THREAD

**Issue by kui4405** [aleh/usbisp#6]
I bought a USBisp Chinese clone a few days ago. There is a "MX-USBISP-V5.00" label on the back of the PCB. Can this firmware also work on it?

**Comment by aleh** [comment]
Hey! No idea, I don't have this one to try and trying is probably the easiest way to verify in this case. Maybe if you could take photos of both sides, then I could at least do some basic comparison?

**Comment by kui4405** [comment]
Hi aleh,
There are photos of both sides.
![front side](https://i.imgur.com/GCdlMi8.jpg)
![back side](https://i.imgur.com/PClSGMn.jpg)

**Comment by kui4405** [comment]
Hi aleh,
Thank for your help.
I try to update the firmware on the PCB shown "MX-USBISP-V5.00" label. 
It looks good, AVRDUDE can recognize USBasp device.
And AVR programmer function also works great. 
![good](https://i.imgur.com/ttW8LX7.jpg)

**Comment by aleh** [comment]
@erokui Sorry for the delay. Thanks for the photos! I've compared them with v 4.00 here and there are just small differences in the routing of the components. Thanks for trying to flash it and reporting here! I've added a note from you into the README.

**Comment by KGKG69** [comment]
how did you update USB ISP v5.00? Please provide steps or link to steps.

**Comment by chaveiro** [comment]
To use with the clone USB ISP v5.00 that have a 0ohm resistor shunting USB D- pin to PD3 disabling USB communications, you can remove the resistor or modify the code to initialize the DDRD value of PD3 as an input instead of output.

Alternative just mod the compiled ATmega88 HEX file, the corresponding code is located on line 185, and here’s the line with the bytes highlighted:
:100B8000D9F77A9589F708951BB815B88BEF8AB90C
Patch the code to set DDRD = 0b1111_0000, thus the corresponding new bytes should be 0x80EF and the correct checksum for that line should now be 0x17:
:100B8000D9F77A9589F708951BB815B880EF8AB917

Source: https://irq5.io/2017/07/25/making-usbasp-chinese-clones-usable/

**Comment by Oldbenone** [comment]
*/
> To use with the clone USB ISP v5.00 that have a 0ohm resistor shunting USB D- pin to PD3 disabling USB communications, you can remove the resistor or modify the code to initialize the DDRD value of PD3 as an input instead of output.
> 
> Alternative just mod the compiled ATmega88 HEX file, the corresponding code is located on line 185, and here’s the line with the bytes highlighted: :100B8000D9F77A9589F708951BB815B88BEF8AB90C Patch the code to set DDRD = 0b1111_0000, thus the corresponding new bytes should be 0x80EF and the correct checksum for that line should now be 0x17: :100B8000D9F77A9589F708951BB815B880EF8AB917
> 
> Source: https://irq5.io/2017/07/25/making-usbasp-chinese-clones-usable/
/*


This worked for Me, My USB ISP is purple with V5.00 on PCB with Atmel Mega88v 10MU1029 chip 12mhz crystal and the 0ohm resistor had a marking A on the silk screen. (I chose to edit hex instead of removing resistor).
I edited the usbasp.atmega88.2011-05-28.hex file for my device with notepad++ went to line 185 copied the above modified line and pasted it over line 185 and saved the hex and uploaded it.
At first I tried loading the original (un-edited) hex and the blue led came on but no USB device found.

I used AVRDUDESS 2.14 in windows with an Arduino Nano programmed as an ISP and  set as an ATMEL AVR ISP in AVRDUDESS.

Thank you aleh so much for making this and the support from chaveiro

**Comment by NBPat** [comment]
I have a dongle with ATmega8 chip.  Same PCB as above but different components used.  
On usb it tries to be   vendor VID usbvid=0x03EB and product PID usbpid=0xC8B4

![atmega8dongle](https://user-images.githubusercontent.com/50875140/229305674-5a0807f0-b5b9-4a37-82a3-92a885dc449b.png)
